env: 'production'
destination: '.tmp'
title: "CartoDB Docs"
description: "Get the most out of CartoDB with our API, examples gallery and documentation. CartoDB is made with love by developers, for everyone"
baseurl: ""
url: "http://docs.cartodb.com"
keywords: "postgresql, postgis, vector, gis, geo, mapping, html5, developer-tools, postgres"

markdown: kramdown
# permalink: pretty
encoding: utf-8
exclude: ['README.md', 'CONTRIBUTING.md', 'config.rb', 'Gemfile', 'Gemfile.lock', 'node_modules', 'bower_components', 'Gruntfile.js', 'package.json', 'docs_build.sh', 's3_website.yml', 'grunt-aws.example.json', 'grunt-aws.json']
highlighter: rouge
gems:
  - jekyll-redirect-from

cartodb-baseurl: 'http://cartodb.com'
academy-baseurl: 'http://academy.cartodb.com'
blog-baseurl: 'http://blog.cartodb.com'

analytics_property_id: UA-20934186-3
mixpanel_token: 9b1d8a4fb14fa98d50615108b8b0161a

collections:
  tutorials:
    output: true
  cartodb-platform:
    output: true

defaults:
  -
    scope:
      path: ""
      type: cartodb-platform
    values:
      js_asset: "editor"
  -
    scope:
      path: ""
      type: tutorials
    values:
      tags: "cartodb, learning, tutorials, documentation, advanced, geospatial, functions"
      js_asset: "index"
  -
    scope:
      path: ""
      type: cartodb-platform
    values:
      layout: platform_item
